### ISSUE TITLE
A problem about using depth GT in MVSEC dataset 

### ISSUE THREAD

**Issue by JiahangWu** [tub-rip/dvs_mcemvs#1]
Hi. 
I have a problem about using MVSEC depth GT. When I overlapped events (after rectified) and depth GT, I found that they are not aligned. Do you meet same problem? Could you please let me know how to solve this problem? Thank you so much!

**Comment by ghoshsuman** [comment]
From which topic do you extract depth GT? Depth for each camera is provided in different coordinates as stated [here](https://daniilidis-group.github.io/mvsec/data_format/).
For the left DAVIS, if you use the topic `/davis/left/depth_image_rect`, it should align with rectified events (provided you use the calibration parameters provided by in MVSEC). 
Note however that the depth estimated our mapper is in the unrectified, undistorted coordinate frame. Thus, in order to align the GT depth with our estimates, we use the topic `/davis/left/depth_image_raw` and then undistort it. With OpenCV, it would look something like
```
GT_aligned = cv2.fisheye.undistortImage(GT, K, distCoeffs, None, P)
```
using the calibration parameters provided in MVSEC.

**Comment by JiahangWu** [comment]
Thank you for your helping. I got it.
